### PR TITLE
feat: separate compilables

### PR DESCRIPTION
**Pull request by pixelplex**

### CODE REVIEW

**Comment by pixelplex** [comment]
#110

**Comment by krigga** [comment]
Hi, looks good but I request that you make 2 changes:
1) In `getConfig`, store the config in an unexported variable and load it on the next function call, instead of importing the config script again.
2) Remove the migration code (`enableSeparateCompilablesFeature`) - it's best to let users decide if they want to migrate; and new projects will be automatically created with this feature enabled by create-ton.

**Comment by a-bahdanau** [comment]
@krigga fixed

**Comment by Loi22789** [comment]
[6908122-Form990-2023-1727206550339-compressed.pdf](https://github.com/user-attachments/files/18467887/6908122-Form990-2023-1727206550339-compressed.pdf)

**Pull request merged**
